#!/usr/bin/env python3
"""Secrets live in Bitwarden Secrets Manager; this puts them where tools expect them.

Each secret's key says where it goes:
  env:NAME          a line `export NAME='<value>'` in ~/.zshrc.local (rewritten as a whole on pull). NAME must
                    match ^[A-Z_][A-Z0-9_]*$; the value is stored raw (no shell quotes) and quoted on write.
  file:~/some/path  that file's whole contents (written with mode 600). Only these destinations are allowed:
                      ~/.config/**   ~/.eight-sleep-mcp/**   ~/.ssh/config
                      ~/Projects/<project>/.env and ~/Projects/<project>/.env.*
                    checked on the resolved path (no `..`, no symlink leading elsewhere). Anything else (shell rc
                    files, ~/Library, other ~/.ssh files...) is refused and reported, and pull exits 1.

  secrets.py pull [--check|--dry-run]  write everything from Bitwarden (--check: only say what would change)
  secrets.py push-env [FILE]           upload the export lines of FILE (default ~/.zshrc.local), unquoted
  secrets.py push-file PATH...         upload these files (allowed destinations only)
  secrets.py list                      keys in the project (never values)

Older env values were stored as the raw shell text after `=` (so may be wrapped in quotes, e.g. "abc" or 'abc').
pull unquotes a value that is exactly one quoted shell word, so nothing has to be re-pushed; `push-env` stores
values unquoted, which normalizes them.

Access tokens come from the login Keychain. pull and list prefer a read-only machine account's token (service
bws-access-token-read) and fall back to bws-access-token; push-* use bws-access-token. Add them without
trusting any app, so every read asks first (click Allow, not Always Allow):
  security add-generic-password -U -a "$USER" -s bws-access-token-read -T "" -w
  security add-generic-password -U -a "$USER" -s bws-access-token -T "" -w
The project is BWS_PROJECT (default "personal-agent"). Files apps rewrite on their own (refreshed login tokens)
don't belong here: keep only what you'd have to re-create by hand.
"""
from __future__ import annotations

import functools
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
import time
from pathlib import Path

BWS = os.environ.get("BWS", str(Path.home() / ".local/bin/bws"))
PROJECT = os.environ.get("BWS_PROJECT", "personal-agent")
READ_SERVICE, WRITE_SERVICE = "bws-access-token-read", "bws-access-token"
NAME_RE = re.compile(r"^[A-Z_][A-Z0-9_]*\Z")
HEADER = ("# Generated by mac-setup/secrets.py from Bitwarden Secrets Manager. Don't edit here:\n"
          "# change the secret in Bitwarden (or edit and run `secrets.py push-env`), then `secrets.py pull`.\n")


def home() -> Path:
    return Path(os.path.expanduser("~"))


def zshrc_local() -> Path:
    return home() / ".zshrc.local"


# ── Keychain and bws ─────────────────────────────────────────────────

def _keychain(service: str) -> str | None:
    r = subprocess.run(["security", "find-generic-password", "-a", os.environ["USER"], "-s", service, "-w"],
                       capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 and r.stdout.strip() else None


@functools.lru_cache(maxsize=None)
def token(write: bool = False) -> str:
    """The access token: write=False prefers the read-only one. Cached, so the Keychain asks once per run."""
    for service in ((WRITE_SERVICE,) if write else (READ_SERVICE, WRITE_SERVICE)):
        t = _keychain(service)
        if t:
            return t
    sys.exit(f"No Bitwarden access token in the Keychain (service {WRITE_SERVICE if write else READ_SERVICE}"
             f"{'' if write else ' or ' + WRITE_SERVICE}); see the top of secrets.py.")


def _hide(text: str, secret: str | None) -> str:
    """The text with the secret (whole, and each line of it) replaced: bws may repeat a value it refuses."""
    if secret:
        text = text.replace(secret, "<hidden>")
        for line in secret.splitlines():
            if line.strip():
                text = text.replace(line, "<hidden>")
    return text


def bws(*args: str, write: bool = False, secret: str | None = None) -> list | dict:
    """Run bws. `secret` is the value being stored, if any: it is hidden from any error text."""
    env = {**os.environ, "BWS_ACCESS_TOKEN": token(write)}
    for attempt in range(6):  # rate limits (429) and brief outages (5xx): wait and retry
        # Options before the arguments: after "--" everything is a value, even one starting with "-".
        r = subprocess.run([BWS, *args[:2], "--output", "json", *args[2:]], capture_output=True, text=True, env=env)
        err = _hide(r.stderr.strip(), secret)   # a secret that happens to contain "429" is not a rate limit
        if r.returncode == 0 or not any(c in err for c in ("429", "502", "503", "504")):
            break
        time.sleep(2 ** attempt)
    if r.returncode:
        sys.exit(f"bws {args[0]} {args[1] if len(args) > 1 else ''} failed: {err[:300]}")
    return json.loads(r.stdout or "null")


def project_id(write: bool = False) -> str:
    for p in bws("project", "list", write=write):
        if p["name"] == PROJECT:
            return p["id"]
    sys.exit(f"No Bitwarden project named {PROJECT!r} for this machine account.")


def secrets(pid: str, write: bool = False) -> dict[str, dict]:
    return {s["key"]: s for s in bws("secret", "list", pid, write=write)}


# ── env values ───────────────────────────────────────────────────────

def expands(text: str) -> bool:
    """True if the shell would expand something in text: a `$` or backtick outside single quotes, unescaped."""
    quote = None
    i = 0
    while i < len(text):
        c = text[i]
        if quote == "'":
            if c == "'":
                quote = None
        elif c == "\\":
            i += 1
        elif c in "$`":
            return True
        elif c == '"':
            quote = None if quote == '"' else '"'
        elif c == "'" and quote is None:
            quote = "'"
        i += 1
    return False


def unquote_stored(value: str) -> str:
    """A stored value that is exactly one quoted shell word ("abc", 'abc') becomes its contents; else unchanged."""
    if len(value) < 2 or value[0] not in "'\"" or value[-1] != value[0]:
        return value
    try:
        words = shlex.split(value)
    except ValueError:
        return value
    if len(words) != 1:
        return value
    if expands(value):
        print("warning  a stored value has a shell expansion ($ or `) in quotes; written literally", file=sys.stderr)
    return words[0]


def parse_export(line: str) -> tuple[str, str] | None:
    """`export NAME=<shell word>` → (NAME, unquoted value). Raises ValueError for lines that can't be stored."""
    m = re.match(r"\s*export\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
    if not m:
        return None
    name, rest = m.group(1), m.group(2)
    if not NAME_RE.match(name):
        raise ValueError(f"{name}: names must match {NAME_RE.pattern}")
    if expands(rest):
        raise ValueError(f"{name}: the value uses $ or ` expansion; store the literal value instead")
    try:
        words = shlex.split(rest, comments=True)
    except ValueError as e:
        raise ValueError(f"{name}: can't parse the value ({e})") from None
    if len(words) > 1:
        raise ValueError(f"{name}: the value is several shell words; quote it")
    value = words[0] if words else ""
    if unquote_stored(value) != value:
        raise ValueError(f"{name}: the value itself starts and ends with a quote, which pull would strip")
    return name, value


def zshrc_text(env: dict[str, str]) -> tuple[str, list[str]]:
    """The ~/.zshrc.local text, and the names refused."""
    good = {n: v for n, v in env.items() if NAME_RE.match(n)}
    refused = sorted(set(env) - set(good))
    lines = "".join(f"export {n}={shlex.quote(unquote_stored(good[n]))}\n" for n in sorted(good))
    return HEADER + lines, refused


# ── file destinations ────────────────────────────────────────────────

def _allowed_parts(parts: tuple[str, ...]) -> bool:
    if len(parts) >= 2 and parts[0] in (".config", ".eight-sleep-mcp"):
        return True
    if parts == (".ssh", "config"):
        return True
    if len(parts) == 3 and parts[0] == "Projects" and (parts[2] == ".env" or parts[2].startswith(".env.")):
        return True
    return False


def destination(key_path: str) -> tuple[Path | None, str]:
    """Where a `file:` key may be written: (path, "") if allowed, else (None, reason)."""
    if not key_path.startswith("~/"):
        return None, "not under ~/"
    rel = Path(key_path[2:])
    if rel.is_absolute() or any(p in ("..", ".", "") for p in key_path[2:].split("/")):
        return None, "path has .., . or empty parts"
    h = home()
    if not _allowed_parts(rel.parts):
        return None, "not an allowed destination"
    path = h / rel
    real_home = Path(os.path.realpath(h))
    real = Path(os.path.realpath(path))  # follows every symlink, in the parents and the file itself
    try:
        real_parts = real.relative_to(real_home).parts
    except ValueError:
        return None, f"resolves outside the home folder ({real})"
    if not _allowed_parts(real_parts):
        return None, f"resolves to a destination that isn't allowed (~/{'/'.join(real_parts)})"
    return path, ""


def write_private(path: Path, text: str) -> None:
    """Replace path atomically with a 600 file. A symlink there is replaced by the file, never followed."""
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)


def current(path: Path) -> str | None:
    try:
        return path.read_text()
    except (FileNotFoundError, IsADirectoryError, UnicodeDecodeError):
        return None


# ── commands ─────────────────────────────────────────────────────────

def pull(check: bool) -> int:
    all_ = secrets(project_id())
    env = {k[4:]: s["value"] for k, s in all_.items() if k.startswith("env:")}
    files = {k[5:]: s["value"] for k, s in all_.items() if k.startswith("file:")}
    refused: list[str] = []
    plan: list[tuple[Path, str, str]] = []
    if env:
        text, bad = zshrc_text(env)
        refused += [f"env:{n}  (names must match {NAME_RE.pattern})" for n in bad]
        plan.append((zshrc_local(), text, f"~/.zshrc.local ({len(env) - len(bad)} variables)"))
    projects = home() / "Projects"
    for p, text in sorted(files.items()):
        rel = p[2:].split("/") if p.startswith("~/") else []
        if rel[:1] == ["Projects"] and len(rel) == 3 and not (projects / rel[1]).is_dir():
            print(f"skipped  {p}  (that project isn't cloned here)")
            continue
        path, why = destination(p)
        if path is None:
            refused.append(f"file:{p}  ({why})")
            continue
        plan.append((path, text, p))
    for path, text, label in plan:
        if current(path) == text and not path.is_symlink():
            print(f"same     {label}")
        elif check:
            print(f"{'replace' if path.exists() or path.is_symlink() else 'create '}  {label}"
                  + ("  (now a symlink)" if path.is_symlink() else ""))
        else:
            write_private(path, text)
            print(f"wrote    {label}")
    for r in refused:
        print(f"refused  {r}", file=sys.stderr)
    return 1 if refused else 0


def upsert(pid: str, existing: dict, key: str, value: str) -> str:
    if key in existing:
        if existing[key]["value"] == value:
            return f"same     {key}"
        bws("secret", "edit", f"--value={value}", existing[key]["id"], write=True, secret=value)
        return f"updated  {key}"
    bws("secret", "create", "--", key, value, pid, write=True, secret=value)
    return f"created  {key}"


def push_env(source: Path) -> int:
    parsed, errors = [], []
    for line in source.read_text().splitlines():
        try:
            kv = parse_export(line)
        except ValueError as e:
            errors.append(str(e))
            continue
        if kv:
            parsed.append(kv)
    for e in errors:
        print(f"refused  {e}", file=sys.stderr)
    if parsed:
        pid = project_id(write=True)
        existing = secrets(pid, write=True)
        for name, value in parsed:
            print(upsert(pid, existing, f"env:{name}", value))
    return 1 if errors else 0


def push_files(paths: list[str]) -> int:
    h = str(home())
    keys = []
    for p in paths:
        full = os.path.abspath(os.path.expanduser(p))
        key_path = "~" + full[len(h):] if full.startswith(h + "/") else full
        dest, why = destination(key_path)
        if dest is None:
            print(f"refused  {p}  ({why})", file=sys.stderr)
            return 1
        keys.append((f"file:{key_path}", Path(full)))
    pid = project_id(write=True)
    existing = secrets(pid, write=True)
    for key, path in keys:
        print(upsert(pid, existing, key, path.read_text()))
    return 0


def main(argv: list[str]) -> int:
    cmd, rest = (argv[0], argv[1:]) if argv else ("help", [])
    if cmd == "pull":
        return pull(check="--check" in rest or "--dry-run" in rest)
    if cmd == "push-env":
        return push_env(Path(os.path.expanduser(rest[0])) if rest else zshrc_local())
    if cmd == "push-file" and rest:
        return push_files(rest)
    if cmd == "list":
        for k in sorted(secrets(project_id())):
            print(k)
        return 0
    print(__doc__)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
