#!/usr/bin/env python3
"""Secrets live in Bitwarden Secrets Manager; this puts them where tools expect them.

Each secret's key says where it goes:
  env:NAME          a line `export NAME=<value>` in ~/.zshrc.local (rewritten as a whole on pull)
  file:~/some/path  that file's whole contents (written with mode 600)

  secrets.py pull [--check]          write everything from Bitwarden (--check: only say what would change)
  secrets.py push-env [FILE]         upload the export lines of FILE (default ~/.zshrc.local)
  secrets.py push-file PATH...       upload these files
  secrets.py list                    keys in the project (never values)

The machine account's access token is read from the login Keychain (service bws-access-token; add it with
`security add-generic-password -U -a "$USER" -s bws-access-token -T /usr/bin/security -w`). The project is
BWS_PROJECT (default "personal-agent"). Files apps rewrite on their own (refreshed login tokens) don't belong
here: keep only what you'd have to re-create by hand.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

BWS = os.environ.get("BWS", str(Path.home() / ".local/bin/bws"))
PROJECT = os.environ.get("BWS_PROJECT", "personal-agent")
ZSHRC_LOCAL = Path.home() / ".zshrc.local"
HEADER = ("# Generated by mac-setup/secrets.py from Bitwarden Secrets Manager. Don't edit here:\n"
          "# change the secret in Bitwarden (or edit and run `secrets.py push-env`), then `secrets.py pull`.\n")


def token() -> str:
    r = subprocess.run(["security", "find-generic-password", "-a", os.environ["USER"], "-s", "bws-access-token", "-w"],
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit("No Bitwarden access token in the Keychain (service bws-access-token); see the top of secrets.py.")
    return r.stdout.strip()


def bws(*args: str) -> list | dict:
    env = {**os.environ, "BWS_ACCESS_TOKEN": token()}
    for attempt in range(6):  # rate limits (429) and brief outages (5xx): wait and retry
        r = subprocess.run([BWS, *args, "--output", "json"], capture_output=True, text=True, env=env)
        if r.returncode == 0 or not any(c in r.stderr for c in ("429", "502", "503", "504")):
            break
        time.sleep(2 ** attempt)
    if r.returncode:
        sys.exit(f"bws {args[0]} {args[1] if len(args) > 1 else ''} failed: {r.stderr.strip()[:300]}")
    return json.loads(r.stdout or "null")


def project_id() -> str:
    for p in bws("project", "list"):
        if p["name"] == PROJECT:
            return p["id"]
    sys.exit(f"No Bitwarden project named {PROJECT!r} for this machine account.")


def secrets(pid: str) -> dict[str, dict]:
    return {s["key"]: s for s in bws("secret", "list", pid)}


def expand(path: str) -> Path:
    return Path(os.path.expanduser(path))


def write_private(path: Path, text: str) -> None:
    """Replace path atomically with a 600 file (a symlink there, e.g. into an old secrets folder, is replaced too)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)


def current(path: Path) -> str | None:
    try:
        return path.read_text()
    except (FileNotFoundError, IsADirectoryError, UnicodeDecodeError):
        return None


def pull(check: bool) -> None:
    all_ = secrets(project_id())
    env = {k[4:]: s["value"] for k, s in all_.items() if k.startswith("env:")}
    files = {k[5:]: s["value"] for k, s in all_.items() if k.startswith("file:")}
    plan = []
    if env:
        text = HEADER + "".join(f"export {name}={env[name]}\n" for name in sorted(env))
        plan.append((ZSHRC_LOCAL, text, f"~/.zshrc.local ({len(env)} variables)"))
    for p, text in sorted(files.items()):
        plan.append((expand(p), text, p))
    projects = Path.home() / "Projects"
    for path, text, label in plan:
        if path.is_relative_to(projects) and path != projects and not (projects / path.relative_to(projects).parts[0]).is_dir():
            print(f"skipped  {label}  (that project isn't cloned here)")
            continue
        same = current(path) == text and not path.is_symlink()
        if same:
            print(f"same     {label}")
        elif check:
            print(f"{'replace' if path.exists() or path.is_symlink() else 'create '}  {label}"
                  + ("  (now a symlink)" if path.is_symlink() else ""))
        else:
            write_private(path, text)
            print(f"wrote    {label}")


def upsert(pid: str, existing: dict, key: str, value: str) -> str:
    if key in existing:
        if existing[key]["value"] == value:
            return f"same     {key}"
        bws("secret", "edit", existing[key]["id"], "--value", value)
        return f"updated  {key}"
    bws("secret", "create", key, value, pid)
    return f"created  {key}"


def push_env(source: Path) -> None:
    pid = project_id()
    existing = secrets(pid)
    for line in source.read_text().splitlines():
        m = re.match(r"\s*export\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if m:
            value = re.sub(r"\s+#.*$", "", m.group(2)).strip()  # drop a trailing comment
            print(upsert(pid, existing, f"env:{m.group(1)}", value))


def push_files(paths: list[str]) -> None:
    pid = project_id()
    existing = secrets(pid)
    home = str(Path.home())
    for p in paths:
        path = expand(p).resolve() if expand(p).is_symlink() else expand(p)
        key = "file:" + (("~" + str(expand(p))[len(home):]) if str(expand(p)).startswith(home) else str(expand(p)))
        print(upsert(pid, existing, key, path.read_text()))


def main(argv: list[str]) -> None:
    cmd, rest = (argv[0], argv[1:]) if argv else ("help", [])
    if cmd == "pull":
        pull(check="--check" in rest)
    elif cmd == "push-env":
        push_env(expand(rest[0]) if rest else ZSHRC_LOCAL)
    elif cmd == "push-file" and rest:
        push_files(rest)
    elif cmd == "list":
        for k in sorted(secrets(project_id())):
            print(k)
    else:
        print(__doc__)


if __name__ == "__main__":
    main(sys.argv[1:])
